### PR TITLE
Alternative database envs

### PR DESCRIPTION
**Pull request by blankse**
Support for `DATABASE_NAME`, `DATABASE_HOST`, `DATABASE_USER`, `DATABASE_PASSWORD` and `DATABASE_PORT` envs.

### CODE REVIEW

**Comment by kszymukowicz** [comment]
Actually IMO drivers should do too much and should be specialized. You can replace driver by choosing other driver class in `db_database`. The current setting for `db_database` from `deployer-extended-symfony4` is:

```
set('db_databases',
    [
        'database_default' => [
            get('db_defaults'),
            (new \SourceBroker\DeployerExtendedSymfony4\Drivers\Symfony4Driver)->getDatabaseConfig(),
        ]
    ]
);
```

but you can overwrite it in your `deploy.php` and use other driver:
```
set('db_databases',
    [
        'database_default' => [
            get('db_defaults'),
            (new \SourceBroker\DeployerExtendedDatabase\Driver\EnvDriver)->getDatabaseConfig(),
        ]
    ]
);
```

**Comment by blankse** [comment]
I think we can't override it without also execute it in the `set.php`

So I must define the envs in both ways.
Otherwise I get an exception.

**Comment by kszymukowicz** [comment]
You right. I fixed that in master.
Try overwrite now.

**Comment by blankse** [comment]
Now it works with overwriting. Thank you!

**Comment by blankse** [comment]
@kszymukowicz Will there be a release/tag with these changes in the near future?

**Comment by kszymukowicz** [comment]
Yes. Next week.

**Comment by blankse** [comment]
@kszymukowicz Is the release coming this week? Or next week?

**Comment by kszymukowicz** [comment]
2.0.0. released just now.

**Comment by blankse** [comment]
@kszymukowicz Thank you 👍🏼

**Pull request closed without merging**
